// Mock data — recipes, brewing stages, telemetry seeds.

const RECIPES = [
  {
    no: '03',
    method: 'Hario V60',
    name: 'Yirgacheffe',
    region: 'Ethiopia · Idido',
    note: 'Bergamot, jasmine, a clean lemon finish that lingers.',
    dose: 20, water: 320, temp: 93,
    ratio: '1 : 16',
    grind: 'Medium-fine · 18 clicks',
    total: '3:00',
    favourite: true,
    tags: ['Pour-over', 'Single origin', 'Floral'],
    stages: [
      { kind: 'Bloom',  to: 30,  water: 40,  label: 'Bloom' },
      { kind: 'Pour',   to: 70,  water: 140, label: 'First pour' },
      { kind: 'Pause',  to: 90,  water: 140, label: 'Pause' },
      { kind: 'Pour',   to: 130, water: 240, label: 'Second pour' },
      { kind: 'Pause',  to: 150, water: 240, label: 'Pause' },
      { kind: 'Pour',   to: 180, water: 320, label: 'Final pour' },
    ],
  },
  {
    no: '07',
    method: 'Hario V60',
    name: 'Geisha',
    region: 'Panama · Hartmann',
    note: 'Ripe peach, jasmine tea, honeysuckle on the cool finish.',
    dose: 18, water: 300, temp: 92,
    ratio: '1 : 16.6',
    grind: 'Medium-fine · 16 clicks',
    total: '3:15',
    favourite: true,
    tags: ['Pour-over', 'Competition', 'Floral'],
  },
  {
    no: '11',
    method: 'Kalita Wave',
    name: 'Kona Extra Fancy',
    region: 'Hawaii · Greenwell',
    note: 'Toasted almond and stone fruit — heavier body, mellow acidity.',
    dose: 22, water: 330, temp: 94,
    ratio: '1 : 15',
    grind: 'Medium · 22 clicks',
    total: '3:30',
    tags: ['Pour-over', 'Single origin', 'Nutty'],
  },
  {
    no: '14',
    method: 'Hario V60',
    name: 'Sidamo Natural',
    region: 'Ethiopia · Guji',
    note: 'Strawberry jam and blackcurrant; syrupy, almost wine-like.',
    dose: 21, water: 330, temp: 92,
    ratio: '1 : 15.7',
    grind: 'Medium · 20 clicks',
    total: '3:20',
    tags: ['Pour-over', 'Natural', 'Fruit-forward'],
  },
  {
    no: '18',
    method: 'Origami Dripper',
    name: 'Caturra Honey',
    region: 'Costa Rica · Tarrazú',
    note: 'Brown sugar, baked apple, a clean cocoa close.',
    dose: 19, water: 285, temp: 93,
    ratio: '1 : 15',
    grind: 'Medium-fine · 17 clicks',
    total: '2:55',
    tags: ['Pour-over', 'Honey process', 'Sweet'],
  },
  {
    no: '22',
    method: 'Kalita Wave',
    name: 'Bourbon Washed',
    region: 'Rwanda · Nyamasheke',
    note: 'Black tea, stone fruit, a long honeyed aftertaste.',
    dose: 20, water: 320, temp: 93,
    ratio: '1 : 16',
    grind: 'Medium-fine · 19 clicks',
    total: '3:10',
    tags: ['Pour-over', 'Washed', 'Tea-like'],
  },
  {
    no: '25',
    method: 'Hario V60',
    name: 'SL-28 Peaberry',
    region: 'Kenya · Nyeri',
    note: 'Blackcurrant and tomato — high acidity, a sharp pour-over.',
    dose: 20, water: 300, temp: 94,
    ratio: '1 : 15',
    grind: 'Fine · 14 clicks',
    total: '3:25',
    tags: ['Pour-over', 'Bright', 'Acid-forward'],
  },
  {
    no: '29',
    method: 'Hario V60',
    name: 'Sumatra Mandheling',
    region: 'Indonesia · Lake Toba',
    note: 'Cedar, dark chocolate, a heavier earthen body.',
    dose: 22, water: 330, temp: 94,
    ratio: '1 : 15',
    grind: 'Medium-coarse · 24 clicks',
    total: '3:40',
    tags: ['Pour-over', 'Wet-hulled', 'Earthy'],
  },
  {
    no: '32',
    method: 'Hario V60',
    name: 'Geisha Anaerobic',
    region: 'Colombia · Tolima',
    note: 'Lychee, white grape, a sparkling effervescent finish.',
    dose: 18, water: 280, temp: 91,
    ratio: '1 : 15.5',
    grind: 'Fine · 13 clicks',
    total: '3:05',
    tags: ['Pour-over', 'Anaerobic', 'Experimental'],
  },
  {
    no: '36',
    method: 'Kalita Wave',
    name: 'Yellow Bourbon',
    region: 'Brazil · Carmo de Minas',
    note: 'Hazelnut, milk chocolate, gentle citrus on the back.',
    dose: 21, water: 315, temp: 93,
    ratio: '1 : 15',
    grind: 'Medium · 21 clicks',
    total: '3:00',
    tags: ['Pour-over', 'Pulped natural', 'Chocolate'],
  },
  {
    no: '41',
    method: 'Origami Dripper',
    name: 'Pink Bourbon',
    region: 'Colombia · Huila',
    note: 'Raspberry, rose, a tart pomegranate finish.',
    dose: 20, water: 300, temp: 92,
    ratio: '1 : 15',
    grind: 'Medium-fine · 18 clicks',
    total: '3:10',
    tags: ['Pour-over', 'Washed', 'Floral'],
  },
  {
    no: '44',
    method: 'Hario V60',
    name: 'Tabi Lactic',
    region: 'Colombia · Quindío',
    note: 'Yogurt, white peach, a creamy lactic body.',
    dose: 19, water: 290, temp: 91,
    ratio: '1 : 15.3',
    grind: 'Medium-fine · 17 clicks',
    total: '3:05',
    tags: ['Pour-over', 'Lactic', 'Experimental'],
  },
];

// Pour log for the recipe-detail screen — represents what the operator sees mid-pour.
const POUR_LOG = [
  { t: '00:00', stage: 'Bloom',   target: 40,  delta: '+40g',  flow: 4.2, temp: 93 },
  { t: '00:30', stage: 'Pause',   target: 40,  delta: '——',    flow: 0.0, temp: 92 },
  { t: '00:45', stage: 'Pour 2',  target: 160, delta: '+120g', flow: 5.1, temp: 93 },
  { t: '01:30', stage: 'Pause',   target: 160, delta: '——',    flow: 0.0, temp: 92 },
  { t: '01:45', stage: 'Pour 3',  target: 240, delta: '+80g',  flow: 4.8, temp: 93 },
  { t: '02:20', stage: 'Pause',   target: 240, delta: '——',    flow: 0.0, temp: 92 },
  { t: '02:30', stage: 'Pour 4',  target: 320, delta: '+80g',  flow: 4.6, temp: 93 },
  { t: '03:00', stage: 'Drawdown',target: 320, delta: '——',    flow: 0.0, temp: 91 },
];

// Image URLs — Unsplash, will be self-hosted later.
const PHOTOS = {
  v60_pour:    'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?w=900&auto=format&fit=crop',
  pour_close:  'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop',
  beans:       'https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=600&auto=format&fit=crop',
  cup_top:     'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&auto=format&fit=crop',
  scale:       'https://images.unsplash.com/photo-1559525839-d9acfd02919b?w=600&auto=format&fit=crop',
  dripper:     'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=600&auto=format&fit=crop',
};

Object.assign(window, { RECIPES, POUR_LOG, PHOTOS });
